version: 1
builder:
  configs:
    - platform: ios
      swift_version: "6.0"
    - platform: macos
      swift_version: "6.0"
    - platform: tvos
      swift_version: "6.0"
    - platform: watchos
      swift_version: "6.0"
