included:
  - Sources
  - Tests

excluded:
  - .build

disabled_rules:
  - identifier_name
  - force_unwrapping
  - file_length
  - type_body_length

line_length:
  warning: 150
  error: 200

function_body_length:
  warning: 60
  error: 100

nesting:
  type_level: 3
